networks:
  dev:

services:
  nginx1:
    image: nginx:stable-alpine
    ports:
      - "4260:4260"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./server
    networks:
      - dev

  frontend:
    build:
      context: ./client
    networks:
      - dev
