services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jwtuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jwt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - my_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
