version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  frontend:
    build: ./client
    ports:
      - "8005:8005"
    depends_on:
      - backend
